name: Test it out
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  start:
    runs-on: ubuntu-latest
    name: Start

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'nicolargo/docker-influxdb-grafana'
          path: 'docker-influxdb-grafana'
      
      - name: run localtunnel
        run: |
          npx localtunnel --port 3000

      - uses: vladkosinov/github-action-daemon@v1.0.0
        with:
          command: |
            sudo mkdir -p /srv/docker/grafana/data && \
            sudo chown -R 472:472 /srv/docker/grafana/data && \
            cd docker-influxdb-grafana && \
            docker-compose up & ./localtunnel-live.sh
