name: Test it out
on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    name: Start

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'nicolargo/docker-influxdb-grafana'
          path: 'docker-influxdb-grafana'
          
      - name: try to run it
        run: |
          sudo mkdir -p /srv/docker/grafana/data
          cd docker-influxdb-grafana
          docker-compose up -d
          sudo chown -R 472:472 /srv/docker/grafana/data
