name: Test it out
on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    name: Start

    steps:
      - uses: actions/checkout@v2

      - name: echo env 
        run: |
          pwd;
          env
