name: Running
on:
  push:
    branches:
      - no
#   schedule:
#     - cron: "0 */1 * * *"

jobs:
  start:
    runs-on: ubuntu-latest
    name: Start

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'docker/awesome-compose'
          path: 'awesome-compose'
      
      - uses: vladkosinov/github-action-daemon@v1.0.0
        with:
          command: |
            ./localtunnel-live.sh & (cd awesome-compose/react-rust-postgres && docker-compose up)
