name: Running
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  start:
    runs-on: ubuntu-latest
    name: Start

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'docker/awesome-compose'
          path: 'awesome-compose'
      
      - uses: vladkosinov/github-action-daemon@v1.0.0
        with:
          command: |
            ./localtunnel-live.sh & (cd awesome-compose/wordpress-mysql && docker-compose up)
